# Generated by Django 5.1.5 on 2025-04-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_challenges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(choices=[('q1', 'What is your favorite color?'), ('q2', "What is your first pet's name?"), ('q3', "What is your mother's maiden name?")], max_length=50),
        ),
    ]
