# Generated by Django 5.2 on 2025-04-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_completed_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(choices=[('q1', 'What is your favorite color?'), ('q2', 'What is your first pet’s name?'), ('q3', "What is your mother's maiden name?")], max_length=50),
        ),
    ]
