# Generated by Django 5.2 on 2025-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='goal_text',
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='steps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='water_intake',
            field=models.PositiveIntegerField(default=0, help_text='oz per day'),
        ),
    ]
