# Generated by Django 5.1.5 on 2025-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_fitnessgoal_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessgoal',
            old_name='calories',
            new_name='daily_calories',
        ),
        migrations.RenameField(
            model_name='fitnessgoal',
            old_name='steps',
            new_name='daily_steps',
        ),
        migrations.RemoveField(
            model_name='fitnessgoal',
            name='water_intake',
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='weekly_miles_goal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='weekly_workout_days_goal',
            field=models.IntegerField(default=0),
        ),
    ]
