# Generated by Django 5.2 on 2025-04-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_calories_fitnessgoal_daily_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='daily_calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='daily_steps',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='weekly_miles_goal',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='weekly_workout_days_goal',
            field=models.IntegerField(default=4),
        ),
    ]
