# Generated by Django 5.1.5 on 2025-04-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('rep-based', 'Rep-based'), ('timed', 'Timed')], default='rep-based', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
