# Generated by Django 5.1.5 on 2025-04-23 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='strava_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repbasedexercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='distance in miles', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='timedexercise',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='distance in miles', max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='StravaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_expires_at', models.DateTimeField()),
                ('athlete_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
