# Generated by Django 5.1.5 on 2025-04-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_duration_minutes_exercise_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight in pounds', max_digits=5, null=True),
        ),
    ]
