# Generated by Django 5.1.5 on 2025-04-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_exercise_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepBasedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('rep-based', 'Rep-based'), ('timed', 'Timed')], max_length=20)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='weight in pounds', max_digits=5, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('rep-based', 'Rep-based'), ('timed', 'Timed')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
