# Generated by Django 5.1.5 on 2025-04-29 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_workoutgroup_created_at_alter_workoutgroup_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_date',
        ),
        migrations.AddField(
            model_name='challenge',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
