# Generated by Django 5.1.5 on 2025-04-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_challenge_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='creator',
        ),
    ]
