# Generated by Django 5.1.5 on 2025-04-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_challenge_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
