# Generated by Django 5.2 on 2025-04-28 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
